# Ecosistema de procesamiento paralelo para datos masivos

## Módulo 3. Lección 2: Programación MapReduce con lenguajes de alto nivel: Hive

### Ejercicios resueltos 2

**IMPORTANTE**

Ejecuta las celdas en orden para evitar errores de ejecución. Esto garantiza que todos los archivos necesarios se creen y se ubiquen correctamente a lo largo del proceso.

#### Obtención de los datos

Utilizamos el dataset Convocatorias y Adjudicaciones

In [1]:
!mkdir -p /media/notebooks/argentina/

In [2]:
# Descargamos el fichero 
! wget https://github.com/Vega90/datasets/raw/main/convocatorias-2020.csv -O \
 /media/notebooks/argentina/convocatorias-2020.csv

--2024-08-28 10:02:41--  https://github.com/Vega90/datasets/raw/main/convocatorias-2020.csv
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/Vega90/datasets/main/convocatorias-2020.csv [following]
--2024-08-28 10:02:42--  https://raw.githubusercontent.com/Vega90/datasets/main/convocatorias-2020.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5675992 (5.4M) [text/plain]
Saving to: ‘/media/notebooks/argentina/convocatorias-2020.csv’

/media/notebooks/ar 100%[===================>]   5.41M  14.5MB/s    in 0.4s

2024-08-28 10:02:43 (14.5 MB/s) - ‘/media/notebooks/argentina/convocatorias-2020.csv’ saved [5675992/5675992]

In [3]:
# Descargamos el fichero 
! wget https://github.com/Vega90/datasets/raw/main/adjudicaciones-2020.csv -O \
 /media/notebooks/argentina/adjudicaciones-2020.csv

--2024-08-28 10:02:43--  https://github.com/Vega90/datasets/raw/main/adjudicaciones-2020.csv
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/Vega90/datasets/main/adjudicaciones-2020.csv [following]
--2024-08-28 10:02:44--  https://raw.githubusercontent.com/Vega90/datasets/main/adjudicaciones-2020.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2659378 (2.5M) [text/plain]
Saving to: ‘/media/notebooks/argentina/adjudicaciones-2020.csv’

/media/notebooks/ar 100%[===================>]   2.54M  12.7MB/s    in 0.2s

2024-08-28 10:02:44 (12.7 MB/s) - ‘/media/notebooks/argentina/adjudicaciones-2020.csv’ saved [2659378/2659378]

In [4]:
# subimos el fichero a HDFS 
! hdfs dfs -mkdir /argentina/adjudicaciones
! hdfs dfs -put /media/notebooks/argentina/adjudicaciones-2020.csv /argentina/adjudicaciones
! hdfs dfs -ls /argentina/adjudicaciones

Found 1 items
-rw-r--r--   3 root supergroup    2659378 2024-08-28 10:02 /argentina/adjudicaciones/adjudicaciones-2020.csv

**Creación carpeta para los ejercicios**

In [5]:
import os
# creamos la carpeta para los ejercicios en local
! mkdir -p /media/notebooks/argentina/hive

# nos vamos a esa carpeta y comprobamos donde estamos
os.chdir("/media/notebooks/argentina/hive")
! pwd

/media/notebooks/argentina/hive

#### Dataframe de pandas para comprender los datos y comparar la salida

Utilizaremos un dataframe de pandas para ayudarnos a entender los datos y también podemos comprobar los ejercicios comparando la salida dada y la salida esperada.

In [2]:
import pandas as pd
# dataframe convocatorias
columnas = [
             'numero_procedimiento', 'nro_saf', 'Descripcion SAF', 'nro_ouc', 
             'descripcion_ouc','tipo-de_procedimiento', 'modalidad', 'apartado_directa', 
             'ejercicio', 'fecha_de_publicacion', 'fecha_de_apertura', 'etapa', 'alcance', 
             'nombre_del_procedimiento', 'objeto_del_procedimiento', 'monto_estimado', 'tipo_de_operacion'
           ]

df_convocatorias = pd.read_csv('/media/notebooks/argentina/convocatorias-2020.csv', names=columnas)

# dataframe adjudicaciones
columnas = [
             'numero_procedimiento', 'nro_saf', 'nro_ouc', 'unidad_ejecutora',  
             'ejercicio_adjudicacion', 'fecha_adjudicacion', 'rubros', 
             'cuit', 'descripcion_proveedor', 'documento_contractual',
             'tipo', 'monto', 'moneda', 'fecha_perfeccionamiento_oc'
           ]

df_adjudicaciones = pd.read_csv('/media/notebooks/argentina/adjudicaciones-2020.csv', names=columnas)

# mostramos los primeros registros 
df_adjudicaciones.head(3)

,numero_procedimiento,nro_saf,nro_ouc,unidad_ejecutora,ejercicio_adjudicacion,fecha_adjudicacion,rubros,cuit,descripcion_proveedor,documento_contractual,tipo,monto,moneda,fecha_perfeccionamiento_oc
0,84/22-1322-LPR20,374,84,84/22 - Comando de Brigada de Monte XII,2020,05/11/2020 12:24:00 p.m.,ALIMENTOS$,20-18053177-8,Federico Pablo Campolongo,84/22-4671-OC20,Original,27164,Peso Argentino,05/11/2020 12:00:00 a.m.
1,340/1-0001-LPR20,376,340,340/001 - Dirección General de Administración ...,2020,28/10/2020 09:58:03 a.m.,CERRAJERIA$ELECTRICIDAD Y TELEFONIA$FERRETERIA...,30-71154458-1,Trigemios S.R.L,340/1-1062-OC20,Original,5610,Peso Argentino,28/10/2020 12:00:00 a.m.
2,38/13-0724-LPR20,379,38,38/13 - Escuela de Tecnicas y Tacticas Navales,2020,30/09/2020 12:31:19 a.m.,CERRAJERIA$EQUIPOS$FERRETERIA$HERRAMIENTAS$IND...,20-290459347-7,DIEGO JULIO PEREZ,38/13-0511-OCA20,SPR,1050,Peso Argentino,30/09/2020 12:47:24 a.m.

#### Creación de la tabla Adjudicaciones.

Lo primero que debemos hacer es crear la tabla con la que realizaremos los ejercicios de esta sección. Para ello es necesario conocer los tipos que tenemos de datos y crear el fichero de consulta adecuado. La tabla *Convocatorias* también debe estar creada en Hive.

In [7]:
%%writefile tabla-adjudicaciones.hql
CREATE EXTERNAL TABLE adjudicaciones (
     numero_procedimiento STRING,
     nro_saf INT,
     nro_uoc INT,
     unidad_ejecutora STRING,
     ejercicio_adjudicacion INT,
     fecha_adjudicacion STRING,
     rubros ARRAY <STRING>,
     cuit STRING,
     descripcion_proveedor STRING,
     documento_contractual STRING,
     tipo STRING,
     monto FLOAT,
     moneda STRING,
     fecha_perfeccionamiento_oc STRING
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
COLLECTION ITEMS TERMINATED BY '$'
STORED AS TEXTFILE
LOCATION '/argentina/adjudicaciones/';

Writing tabla-adjudicaciones.hql

In [8]:
# ejecucion del fichero hql mediante beeline
!beeline -u "jdbc:hive2://" -f tabla-adjudicaciones.hql

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Connecting to jdbc:hive2://
Hive Session ID = 1cc62e2d-7229-41c3-932d-a3bd3c40b3ed
24/08/28 10:03:07 [main]: WARN hikari.HikariConfig: objectstore - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
24/08/28 10:03:08 [main]: WARN hikari.HikariConfig: objectstore-secondary - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
24/08/28 10:03:10 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:10 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:10 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:10 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:10 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:10 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:11 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:11 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:11 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:11 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:11 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:11 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:14 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.cpc.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:03:14 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.hll.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:03:14 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.IntersectSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:03:14 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.EstimateSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:03:14 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.ExcludeSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:03:14 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:03:14 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.tuple.ArrayOfDoublesSketchToValuesUDTF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:03:14 [main]: WARN session.SessionState: Configuration hive.reloadable.aux.jars.path not specified
Connected to: Apache Hive (version 4.0.0)
Driver: Hive JDBC (version 4.0.0)
Transaction isolation: TRANSACTION_REPEATABLE_READ
0: jdbc:hive2://> CREATE EXTERNAL TABLE adjudicaciones (
. . . . . . . . >      numero_procedimiento STRING,
. . . . . . . . >      nro_saf INT,
. . . . . . . . >      nro_uoc INT,
. . . . . . . . >      unidad_ejecutora STRING,
. . . . . . . . >      ejercicio_adjudicacion INT,
. . . . . . . . >      fecha_adjudicacion STRING,
. . . . . . . . >      rubros ARRAY <STRING>,
. . . . . . . . >      cuit STRING,
. . . . . . . . >      descripcion_proveedor STRING,
. . . . . . . . >      documento_contractual STRING,
. . . . . . . . >      tipo STRING,
. . . . . . . . >      monto FLOAT,
. . . . . . . . >      moneda STRING,
. . . . . . . . >      fecha_perfeccionamiento_oc STRING
. . . . . . . . > )
. . . . . . . . > ROW FORMAT DELIMITED
. . . . . . . . > FIELDS TERMINATED BY ','
. . . . . . . . > COLLECTION ITEMS TERMINATED BY '$'
. . . . . . . . > STORED AS TEXTFILE
. . . . . . . . > LOCATION '/argentina/adjudicaciones/';
No rows affected (3.539 seconds)
0: jdbc:hive2://>
0: jdbc:hive2://> Closing: 0: jdbc:hive2://
24/08/28 10:03:18 [shutdown-hook-0]: WARN util.ShutdownHookManager: Shutdown in progress, cannot cancel a deleteOnExit
24/08/28 10:03:19 [shutdown-hook-0]: WARN util.ShutdownHookManager: Shutdown in progress, cannot cancel a deleteOnExit

In [9]:
#mostramos las tres primeas filas
!beeline -u "jdbc:hive2://" -e \
"SELECT numero_procedimiento, unidad_ejecutora, fecha_adjudicacion, monto \
FROM adjudicaciones \
LIMIT 3;"

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Connecting to jdbc:hive2://
Hive Session ID = 310a87c7-361b-4b59-bf9c-d7367c73034d
24/08/28 10:03:27 [main]: WARN hikari.HikariConfig: objectstore - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
24/08/28 10:03:28 [main]: WARN hikari.HikariConfig: objectstore-secondary - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
24/08/28 10:03:29 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:29 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:30 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:30 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:30 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:30 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:30 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:30 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:30 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:30 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:30 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:30 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:33 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.cpc.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:03:33 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.hll.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:03:33 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.IntersectSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:03:33 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.EstimateSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:03:33 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.ExcludeSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:03:33 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:03:33 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.tuple.ArrayOfDoublesSketchToValuesUDTF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:03:34 [main]: WARN session.SessionState: Configuration hive.reloadable.aux.jars.path not specified
Connected to: Apache Hive (version 4.0.0)
Driver: Hive JDBC (version 4.0.0)
Transaction isolation: TRANSACTION_REPEATABLE_READ
24/08/28 10:03:40 [154a63c4-843f-4b94-8c59-62433e5fb086 main]: WARN calcite.RelOptHiveTable: No Stats for default@adjudicaciones, Columns: unidad_ejecutora, monto, numero_procedimiento, fecha_adjudicacion
No Stats for default@adjudicaciones, Columns: unidad_ejecutora, monto, numero_procedimiento, fecha_adjudicacion
24/08/28 10:03:40 [154a63c4-843f-4b94-8c59-62433e5fb086 main]: WARN optimizer.SimpleFetchOptimizer: Table default@adjudicaciones is external table, falling back to filesystem scan.
+-----------------------+----------------------------------------------------+---------------------------+----------+
| numero_procedimiento  |                  unidad_ejecutora                  |    fecha_adjudicacion     |  monto   |
+-----------------------+----------------------------------------------------+---------------------------+----------+
| 84/22-1322-LPR20      | 84/22 - Comando de Brigada de Monte XII            | 05/11/2020 12:24:00 p.m.  | 27164.0  |
| 340/1-0001-LPR20      | 340/001 - Direcci?n General de Administraci?n - SSSLD | 28/10/2020 09:58:03 a.m.  | 5610.0   |
| 38/13-0724-LPR20      | 38/13 - Escuela de Tecnicas y Tacticas Navales     | 30/09/2020 12:31:19 a.m.  | 1050.0   |
+-----------------------+----------------------------------------------------+---------------------------+----------+
3 rows selected (7.005 seconds)
Beeline version 4.0.0 by Apache Hive
Closing: 0: jdbc:hive2://
24/08/28 10:03:41 [shutdown-hook-0]: WARN util.ShutdownHookManager: Shutdown in progress, cannot cancel a deleteOnExit
24/08/28 10:03:41 [shutdown-hook-0]: WARN util.ShutdownHookManager: Shutdown in progress, cannot cancel a deleteOnExit

#### **Ejercicio 07.** Unión de tablas con Apache Hive.

En este ejercicio vamos a realizar la unión de dos tablas para crear una tercera con la que podremos realizar consultas y análisis más profundos. Necesitaremos el campo común a ambas tablas numero_procedimiento y que actúe como clave.

Necesitaremos el campo común a ambas tablas numero_procedimiento. A partir de la consulta, crearemos una nueva tabla que sea la unión de las dos cuando haya coincidencias en ambas tablas (INNER JOIN). Aprovecharemos para ordenar algunas columnas, con el fin de que quede más ordenado y claro.

A continuación, también dejamos el código para crear la tabla Convocatorias, por si no estuvieses creada en Hive.

In [10]:
%%writefile tabla-convocatorias.hql
CREATE EXTERNAL TABLE convocatorias (
     numero_procedimiento STRING,
     nro_saf INT,
     descripcion_saf STRING,
     nro_uoc INT,
     descripcion_uoc STRING,
     tipo_de_procedimiento STRING,
     modalidad STRING,
     apartado_directa STRING,
     ejercicio INT,
     fecha_de_publicacion STRING,
     fecha_de_apertura STRING,
     etapa STRING,
     alcance STRING,
     nombre_del_procedimiento STRING,
     objeto_del_procedimiento STRING,
     monto_estimado FLOAT,
     tipo_de_operacion STRING
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/argentina/convocatorias/'
TBLPROPERTIES ("skip.header.line.count"="0");

Overwriting tabla-convocatorias.hql

In [11]:
%%writefile tabla-nueva.hql
CREATE TABLE tabla_union AS
SELECT
     conv.numero_procedimiento,
     conv.nro_saf AS nro_saf,
     conv.descripcion_saf AS descripcion_saf,
     conv.nro_uoc AS nro_uoc,
     conv.descripcion_uoc AS descripcion_uoc,
     conv.tipo_de_procedimiento AS tipo_de_procedimiento,
     conv.modalidad AS modalidad,
     conv.apartado_directa AS apartado_directa,
     conv.ejercicio AS ejercicio,
     adj.ejercicio_adjudicacion AS ejercicio_adjudicacion,
     conv.fecha_de_publicacion AS fecha_de_publicacion,
     adj.fecha_adjudicacion AS fecha_adjudicacion,
     conv.fecha_de_apertura AS fecha_de_apertura,
     conv.etapa AS etapa,
     conv.alcance AS alcance,
     conv.nombre_del_procedimiento AS nombre_del_procedimiento,
     conv.objeto_del_procedimiento AS objeto_del_procedimiento,
     conv.monto_estimado AS monto_estimado,
     adj.monto AS monto_adjudicado,
     adj.moneda AS moneda_adj,
     conv.tipo_de_operacion AS tipo_de_operacion,
     adj.unidad_ejecutora AS unidad_ejecutora_adj,
     adj.rubros AS rubros,
     adj.cuit AS cuit,
     adj.descripcion_proveedor AS descripcion_proveedor,
     adj.documento_contractual AS documento_contractual
FROM convocatorias AS conv
INNER JOIN adjudicaciones AS adj
ON  conv.numero_procedimiento = adj.numero_procedimiento;

Writing tabla-nueva.hql

In [12]:
# ejecucion del fichero hql mediante beeline
!beeline -u "jdbc:hive2://" -f tabla-convocatorias.hql

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Connecting to jdbc:hive2://
Hive Session ID = c3285d67-4cb8-4b9f-a2c2-376e63a3599b
24/08/28 10:03:50 [main]: WARN hikari.HikariConfig: objectstore - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
24/08/28 10:03:51 [main]: WARN hikari.HikariConfig: objectstore-secondary - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
24/08/28 10:03:52 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:52 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:52 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:52 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:52 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:52 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:53 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:53 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:53 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:53 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:53 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:53 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:03:56 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.cpc.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:03:56 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.hll.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:03:56 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.IntersectSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:03:56 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.EstimateSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:03:56 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.ExcludeSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:03:56 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:03:56 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.tuple.ArrayOfDoublesSketchToValuesUDTF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:03:56 [main]: WARN session.SessionState: Configuration hive.reloadable.aux.jars.path not specified
Connected to: Apache Hive (version 4.0.0)
Driver: Hive JDBC (version 4.0.0)
Transaction isolation: TRANSACTION_REPEATABLE_READ
0: jdbc:hive2://> CREATE EXTERNAL TABLE convocatorias (
. . . . . . . . >      numero_procedimiento STRING,
. . . . . . . . >      nro_saf INT,
. . . . . . . . >      descripcion_saf STRING,
. . . . . . . . >      nro_uoc INT,
. . . . . . . . >      descripcion_uoc STRING,
. . . . . . . . >      tipo_de_procedimiento STRING,
. . . . . . . . >      modalidad STRING,
. . . . . . . . >      apartado_directa STRING,
. . . . . . . . >      ejercicio INT,
. . . . . . . . >      fecha_de_publicacion STRING,
. . . . . . . . >      fecha_de_apertura STRING,
. . . . . . . . >      etapa STRING,
. . . . . . . . >      alcance STRING,
. . . . . . . . >      nombre_del_procedimiento STRING,
. . . . . . . . >      objeto_del_procedimiento STRING,
. . . . . . . . >      monto_estimado FLOAT,
. . . . . . . . >      tipo_de_operacion STRING
. . . . . . . . > )
. . . . . . . . > ROW FORMAT DELIMITED
. . . . . . . . > FIELDS TERMINATED BY ','
. . . . . . . . > STORED AS TEXTFILE
. . . . . . . . > LOCATION '/argentina/convocatorias/'
. . . . . . . . > TBLPROPERTIES ("skip.header.line.count"="0");
24/08/28 10:04:00 [HiveServer2-Background-Pool: Thread-55]: WARN metastore.HMSHandler: create_table_req got
org.apache.hadoop.hive.metastore.api.AlreadyExistsException: Table hive.default.convocatorias already exists
	at org.apache.hadoop.hive.metastore.HMSHandler.create_table_core(HMSHandler.java:2276) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.metastore.HMSHandler.create_table_req(HMSHandler.java:2549) ~[hive-exec-4.0.0.jar:4.0.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_412]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_412]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_412]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_412]
	at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invokeInternal(RetryingHMSHandler.java:91) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.metastore.AbstractHMSHandlerProxy.invoke(AbstractHMSHandlerProxy.java:82) ~[hive-exec-4.0.0.jar:4.0.0]
	at com.sun.proxy.$Proxy36.create_table_req(Unknown Source) ~[?:?]
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.create_table(HiveMetaStoreClient.java:4640) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient.create_table(SessionHiveMetaStoreClient.java:174) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:1490) ~[hive-exec-4.0.0.jar:4.0.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_412]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_412]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_412]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_412]
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:213) ~[hive-exec-4.0.0.jar:4.0.0]
	at com.sun.proxy.$Proxy37.createTable(Unknown Source) ~[?:?]
	at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:1376) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:1388) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.ddl.table.create.CreateTableOperation.createTableNonReplaceMode(CreateTableOperation.java:158) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.ddl.table.create.CreateTableOperation.execute(CreateTableOperation.java:116) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.ddl.DDLTask.execute(DDLTask.java:84) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:214) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:105) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.Executor.launchTask(Executor.java:354) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.Executor.launchTasks(Executor.java:327) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.Executor.runTasks(Executor.java:244) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.Executor.execute(Executor.java:105) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:367) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:205) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:154) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:149) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.reexec.ReExecDriver.run(ReExecDriver.java:185) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hive.service.cli.operation.SQLOperation.runQuery(SQLOperation.java:236) ~[hive-service-4.0.0.jar:4.0.0]
	at org.apache.hive.service.cli.operation.SQLOperation.access$500(SQLOperation.java:90) ~[hive-service-4.0.0.jar:4.0.0]
	at org.apache.hive.service.cli.operation.SQLOperation$BackgroundWork$1.run(SQLOperation.java:336) ~[hive-service-4.0.0.jar:4.0.0]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_412]
	at javax.security.auth.Subject.doAs(Subject.java:422) ~[?:1.8.0_412]
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1953) ~[hadoop-common-3.4.0.jar:?]
	at org.apache.hive.service.cli.operation.SQLOperation$BackgroundWork.run(SQLOperation.java:356) ~[hive-service-4.0.0.jar:4.0.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_412]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_412]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_412]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_412]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_412]
24/08/28 10:04:01 [HiveServer2-Background-Pool: Thread-55]: ERROR metastore.RetryingHMSHandler: AlreadyExistsException(message:Table hive.default.convocatorias already exists)
	at org.apache.hadoop.hive.metastore.HMSHandler.create_table_core(HMSHandler.java:2276)
	at org.apache.hadoop.hive.metastore.HMSHandler.create_table_req(HMSHandler.java:2549)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invokeInternal(RetryingHMSHandler.java:91)
	at org.apache.hadoop.hive.metastore.AbstractHMSHandlerProxy.invoke(AbstractHMSHandlerProxy.java:82)
	at com.sun.proxy.$Proxy36.create_table_req(Unknown Source)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.create_table(HiveMetaStoreClient.java:4640)
	at org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient.create_table(SessionHiveMetaStoreClient.java:174)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:1490)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:213)
	at com.sun.proxy.$Proxy37.createTable(Unknown Source)
	at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:1376)
	at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:1388)
	at org.apache.hadoop.hive.ql.ddl.table.create.CreateTableOperation.createTableNonReplaceMode(CreateTableOperation.java:158)
	at org.apache.hadoop.hive.ql.ddl.table.create.CreateTableOperation.execute(CreateTableOperation.java:116)
	at org.apache.hadoop.hive.ql.ddl.DDLTask.execute(DDLTask.java:84)
	at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:214)
	at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:105)
	at org.apache.hadoop.hive.ql.Executor.launchTask(Executor.java:354)
	at org.apache.hadoop.hive.ql.Executor.launchTasks(Executor.java:327)
	at org.apache.hadoop.hive.ql.Executor.runTasks(Executor.java:244)
	at org.apache.hadoop.hive.ql.Executor.execute(Executor.java:105)
	at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:367)
	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:205)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:154)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:149)
	at org.apache.hadoop.hive.ql.reexec.ReExecDriver.run(ReExecDriver.java:185)
	at org.apache.hive.service.cli.operation.SQLOperation.runQuery(SQLOperation.java:236)
	at org.apache.hive.service.cli.operation.SQLOperation.access$500(SQLOperation.java:90)
	at org.apache.hive.service.cli.operation.SQLOperation$BackgroundWork$1.run(SQLOperation.java:336)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1953)
	at org.apache.hive.service.cli.operation.SQLOperation$BackgroundWork.run(SQLOperation.java:356)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

24/08/28 10:04:01 [HiveServer2-Background-Pool: Thread-55]: ERROR exec.Task: Failed
org.apache.hadoop.hive.ql.metadata.HiveException: AlreadyExistsException(message:Table hive.default.convocatorias already exists)
	at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:1380) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:1388) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.ddl.table.create.CreateTableOperation.createTableNonReplaceMode(CreateTableOperation.java:158) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.ddl.table.create.CreateTableOperation.execute(CreateTableOperation.java:116) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.ddl.DDLTask.execute(DDLTask.java:84) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:214) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:105) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.Executor.launchTask(Executor.java:354) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.Executor.launchTasks(Executor.java:327) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.Executor.runTasks(Executor.java:244) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.Executor.execute(Executor.java:105) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:367) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:205) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:154) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:149) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.reexec.ReExecDriver.run(ReExecDriver.java:185) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hive.service.cli.operation.SQLOperation.runQuery(SQLOperation.java:236) ~[hive-service-4.0.0.jar:4.0.0]
	at org.apache.hive.service.cli.operation.SQLOperation.access$500(SQLOperation.java:90) ~[hive-service-4.0.0.jar:4.0.0]
	at org.apache.hive.service.cli.operation.SQLOperation$BackgroundWork$1.run(SQLOperation.java:336) ~[hive-service-4.0.0.jar:4.0.0]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_412]
	at javax.security.auth.Subject.doAs(Subject.java:422) ~[?:1.8.0_412]
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1953) ~[hadoop-common-3.4.0.jar:?]
	at org.apache.hive.service.cli.operation.SQLOperation$BackgroundWork.run(SQLOperation.java:356) ~[hive-service-4.0.0.jar:4.0.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_412]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_412]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_412]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_412]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_412]
Caused by: org.apache.hadoop.hive.metastore.api.AlreadyExistsException: Table hive.default.convocatorias already exists
	at org.apache.hadoop.hive.metastore.HMSHandler.create_table_core(HMSHandler.java:2276) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.metastore.HMSHandler.create_table_req(HMSHandler.java:2549) ~[hive-exec-4.0.0.jar:4.0.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_412]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_412]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_412]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_412]
	at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invokeInternal(RetryingHMSHandler.java:91) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.metastore.AbstractHMSHandlerProxy.invoke(AbstractHMSHandlerProxy.java:82) ~[hive-exec-4.0.0.jar:4.0.0]
	at com.sun.proxy.$Proxy36.create_table_req(Unknown Source) ~[?:?]
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.create_table(HiveMetaStoreClient.java:4640) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient.create_table(SessionHiveMetaStoreClient.java:174) ~[hive-exec-4.0.0.jar:4.0.0]
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:1490) ~[hive-exec-4.0.0.jar:4.0.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_412]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_412]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_412]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_412]
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:213) ~[hive-exec-4.0.0.jar:4.0.0]
	at com.sun.proxy.$Proxy37.createTable(Unknown Source) ~[?:?]
	at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:1376) ~[hive-exec-4.0.0.jar:4.0.0]
	... 27 more

In [13]:
# ejecucion del fichero hql mediante beeline
!beeline -u "jdbc:hive2://" -f tabla-nueva.hql

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Connecting to jdbc:hive2://
Hive Session ID = 98cc1376-26db-42ce-8a27-396173238727
24/08/28 10:04:10 [main]: WARN hikari.HikariConfig: objectstore - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
24/08/28 10:04:11 [main]: WARN hikari.HikariConfig: objectstore-secondary - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
24/08/28 10:04:13 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:04:13 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:04:13 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:04:13 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:04:13 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:04:13 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:04:13 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:04:13 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:04:13 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:04:13 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:04:13 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:04:13 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:04:16 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.cpc.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:04:16 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.hll.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:04:16 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.IntersectSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:04:16 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.EstimateSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:04:16 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.ExcludeSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:04:16 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:04:16 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.tuple.ArrayOfDoublesSketchToValuesUDTF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:04:17 [main]: WARN session.SessionState: Configuration hive.reloadable.aux.jars.path not specified
Connected to: Apache Hive (version 4.0.0)
Driver: Hive JDBC (version 4.0.0)
Transaction isolation: TRANSACTION_REPEATABLE_READ
0: jdbc:hive2://> CREATE TABLE tabla_union AS
. . . . . . . . > SELECT
. . . . . . . . >      conv.numero_procedimiento,
. . . . . . . . >      conv.nro_saf AS nro_saf,
. . . . . . . . >      conv.descripcion_saf AS descripcion_saf,
. . . . . . . . >      conv.nro_uoc AS nro_uoc,
. . . . . . . . >      conv.descripcion_uoc AS descripcion_uoc,
. . . . . . . . >      conv.tipo_de_procedimiento AS tipo_de_procedimiento,
. . . . . . . . >      conv.modalidad AS modalidad,
. . . . . . . . >      conv.apartado_directa AS apartado_directa,
. . . . . . . . >      conv.ejercicio AS ejercicio,
. . . . . . . . >      adj.ejercicio_adjudicacion AS ejercicio_adjudicacion,
. . . . . . . . >      conv.fecha_de_publicacion AS fecha_de_publicacion,
. . . . . . . . >      adj.fecha_adjudicacion AS fecha_adjudicacion,
. . . . . . . . >      conv.fecha_de_apertura AS fecha_de_apertura,
. . . . . . . . >      conv.etapa AS etapa,
. . . . . . . . >      conv.alcance AS alcance,
, . . . . . . . >      conv.nombre_del_procedimiento AS nombre_del_procedimiento
, . . . . . . . >      conv.objeto_del_procedimiento AS objeto_del_procedimiento
. . . . . . . . >      conv.monto_estimado AS monto_estimado,
. . . . . . . . >      adj.monto AS monto_adjudicado,
. . . . . . . . >      adj.moneda AS moneda_adj,
. . . . . . . . >      conv.tipo_de_operacion AS tipo_de_operacion,
. . . . . . . . >      adj.unidad_ejecutora AS unidad_ejecutora_adj,
. . . . . . . . >      adj.rubros AS rubros,
. . . . . . . . >      adj.cuit AS cuit,
. . . . . . . . >      adj.descripcion_proveedor AS descripcion_proveedor,
. . . . . . . . >      adj.documento_contractual AS documento_contractual
. . . . . . . . > FROM convocatorias AS conv
. . . . . . . . > INNER JOIN adjudicaciones AS adj
. . . . . . . . > ON  conv.numero_procedimiento = adj.numero_procedimiento;
24/08/28 10:04:25 [51a7039c-37ce-496c-be11-b9dabdf68987 main]: WARN calcite.RelOptHiveTable: No Stats for default@convocatorias, Columns: descripcion_uoc, etapa, fecha_de_publicacion, nro_uoc, tipo_de_operacion, ejercicio, alcance, descripcion_saf, objeto_del_procedimiento, modalidad, monto_estimado, tipo_de_procedimiento, numero_procedimiento, nro_saf, apartado_directa, nombre_del_procedimiento, fecha_de_apertura
No Stats for default@convocatorias, Columns: descripcion_uoc, etapa, fecha_de_publicacion, nro_uoc, tipo_de_operacion, ejercicio, alcance, descripcion_saf, objeto_del_procedimiento, modalidad, monto_estimado, tipo_de_procedimiento, numero_procedimiento, nro_saf, apartado_directa, nombre_del_procedimiento, fecha_de_apertura
24/08/28 10:04:25 [51a7039c-37ce-496c-be11-b9dabdf68987 main]: WARN calcite.RelOptHiveTable: No Stats for default@adjudicaciones, Columns: rubros, unidad_ejecutora, ejercicio_adjudicacion, cuit, monto, descripcion_proveedor, moneda, numero_procedimiento, documento_contractual, fecha_adjudicacion
No Stats for default@adjudicaciones, Columns: rubros, unidad_ejecutora, ejercicio_adjudicacion, cuit, monto, descripcion_proveedor, moneda, numero_procedimiento, documento_contractual, fecha_adjudicacion
24/08/28 10:04:26 [HiveServer2-Background-Pool: Thread-54]: WARN ql.Driver: Hive-on-MR is deprecated in Hive 2 and may not be available in the future versions. Consider using a different execution engine (i.e. tez) or using Hive 1.X releases.
Query ID = root_20240828100418_5906adfb-b39b-4bc4-81dd-e54b135feafb
Total jobs = 1
Launching Job 1 out of 1
Number of reduce tasks not specified. Estimated from input data size: 1
In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=<number>
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=<number>
In order to set a constant number of reducers:
  set mapreduce.job.reduces=<number>
WARN  : Hive-on-MR is deprecated in Hive 2 and may not be available in the future versions. Consider using a different execution engine (i.e. tez) or using Hive 1.X releases.
24/08/28 10:04:28 [HiveServer2-Background-Pool: Thread-54]: WARN mapreduce.JobResourceUploader: Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
Starting Job = job_1724833657149_0022, Tracking URL = http://yarnmanager:8088/proxy/application_1724833657149_0022/
Kill Command = /usr/local/hadoop/bin/mapred job  -kill job_1724833657149_0022
Hadoop job information for Stage-1: number of mappers: 2; number of reducers: 1
24/08/28 10:04:48 [HiveServer2-Background-Pool: Thread-54]: WARN mapreduce.Counters: Group org.apache.hadoop.mapred.Task$Counter is deprecated. Use org.apache.hadoop.mapreduce.TaskCounter instead
2024-08-28 10:04:48,361 Stage-1 map = 0%,  reduce = 0%
2024-08-28 10:05:28,709 Stage-1 map = 50%,  reduce = 0%, Cumulative CPU 11.66 sec
2024-08-28 10:05:30,953 Stage-1 map = 100%,  reduce = 0%, Cumulative CPU 24.91 sec
2024-08-28 10:05:40,753 Stage-1 map = 100%,  reduce = 100%, Cumulative CPU 31.19 sec
MapReduce Total cumulative CPU time: 31 seconds 190 msec
Ended Job = job_1724833657149_0022
Moving data to directory hdfs://namenode:9000/user/hive/warehouse/tabla_union
24/08/28 10:05:43 [HiveServer2-Background-Pool: Thread-54]: WARN metadata.Hive: Cannot get a table snapshot for tabla_union
MapReduce Jobs Launched:
Stage-Stage-1: Map: 2  Reduce: 1   Cumulative CPU: 31.19 sec   HDFS Read: 8379440 HDFS Write: 5241792 HDFS EC Read: 0 SUCCESS
Total MapReduce CPU Time Spent: 31 seconds 190 msec
8,633 rows affected (86.06 seconds)
0: jdbc:hive2://>
0: jdbc:hive2://> Closing: 0: jdbc:hive2://
24/08/28 10:05:44 [shutdown-hook-0]: WARN util.ShutdownHookManager: Shutdown in progress, cannot cancel a deleteOnExit
24/08/28 10:05:44 [shutdown-hook-0]: WARN util.ShutdownHookManager: Shutdown in progress, cannot cancel a deleteOnExit

In [14]:
# mostramos las tres primeras filas 
!beeline -u "jdbc:hive2://" -e \
"SELECT numero_procedimiento, nro_saf, ejercicio_adjudicacion, ejercicio \
FROM tabla_union \
LIMIT 3;"

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Connecting to jdbc:hive2://
Hive Session ID = c02de654-fa33-4663-8315-6aa98505ff86
24/08/28 10:05:54 [main]: WARN hikari.HikariConfig: objectstore - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
24/08/28 10:05:55 [main]: WARN hikari.HikariConfig: objectstore-secondary - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
24/08/28 10:05:57 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:05:57 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:05:57 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:05:57 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:05:57 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:05:57 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:05:58 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:05:58 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:05:58 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:05:58 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:05:58 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:05:58 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:06:01 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.cpc.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:06:01 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.hll.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:06:01 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.IntersectSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:06:01 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.EstimateSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:06:01 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.ExcludeSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:06:01 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:06:01 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.tuple.ArrayOfDoublesSketchToValuesUDTF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:06:01 [main]: WARN session.SessionState: Configuration hive.reloadable.aux.jars.path not specified
Connected to: Apache Hive (version 4.0.0)
Driver: Hive JDBC (version 4.0.0)
Transaction isolation: TRANSACTION_REPEATABLE_READ
24/08/28 10:06:08 [1144ae1b-d07e-4824-8353-5b550b842e06 main]: WARN calcite.RelOptHiveTable: No Stats for default@tabla_union, Columns: ejercicio_adjudicacion, numero_procedimiento, nro_saf, ejercicio
No Stats for default@tabla_union, Columns: ejercicio_adjudicacion, numero_procedimiento, nro_saf, ejercicio
24/08/28 10:06:09 [1144ae1b-d07e-4824-8353-5b550b842e06 main]: WARN optimizer.SimpleFetchOptimizer: Table default@tabla_union is external table, falling back to filesystem scan.
+-----------------------+----------+-------------------------+------------+
| numero_procedimiento  | nro_saf  | ejercicio_adjudicacion  | ejercicio  |
+-----------------------+----------+-------------------------+------------+
| 101-0001-CDI20        | 622      | 2020                    | 2020       |
| 101-0002-CDI20        | 622      | 2020                    | 2020       |
| 101-0002-LPR20        | 622      | 2020                    | 2020       |
+-----------------------+----------+-------------------------+------------+
3 rows selected (8.242 seconds)
Beeline version 4.0.0 by Apache Hive
Closing: 0: jdbc:hive2://
24/08/28 10:06:10 [shutdown-hook-0]: WARN util.ShutdownHookManager: Shutdown in progress, cannot cancel a deleteOnExit
24/08/28 10:06:10 [shutdown-hook-0]: WARN util.ShutdownHookManager: Shutdown in progress, cannot cancel a deleteOnExit

In [15]:
# contamos el numero de registros
!beeline -u "jdbc:hive2://" -e \
"SELECT Count(*) as num_registros \
FROM tabla_union;"

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Connecting to jdbc:hive2://
Hive Session ID = da3cb115-6d7a-438e-90b6-beddc385076e
24/08/28 10:06:20 [main]: WARN hikari.HikariConfig: objectstore - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
24/08/28 10:06:20 [main]: WARN hikari.HikariConfig: objectstore-secondary - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
24/08/28 10:06:22 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:06:22 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:06:22 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:06:22 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:06:22 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:06:22 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:06:23 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:06:23 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:06:23 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:06:23 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:06:23 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:06:23 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:06:26 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.cpc.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:06:26 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.hll.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:06:26 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.IntersectSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:06:26 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.EstimateSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:06:26 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.ExcludeSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:06:26 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:06:26 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.tuple.ArrayOfDoublesSketchToValuesUDTF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:06:27 [main]: WARN session.SessionState: Configuration hive.reloadable.aux.jars.path not specified
Connected to: Apache Hive (version 4.0.0)
Driver: Hive JDBC (version 4.0.0)
Transaction isolation: TRANSACTION_REPEATABLE_READ
24/08/28 10:06:34 [HiveServer2-Background-Pool: Thread-52]: WARN ql.Driver: Hive-on-MR is deprecated in Hive 2 and may not be available in the future versions. Consider using a different execution engine (i.e. tez) or using Hive 1.X releases.
Query ID = root_20240828100627_00126587-fa8d-4e07-8760-0316e3039454
Total jobs = 1
Launching Job 1 out of 1
Number of reduce tasks determined at compile time: 1
In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=<number>
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=<number>
In order to set a constant number of reducers:
  set mapreduce.job.reduces=<number>
WARN  : Hive-on-MR is deprecated in Hive 2 and may not be available in the future versions. Consider using a different execution engine (i.e. tez) or using Hive 1.X releases.
24/08/28 10:06:37 [HiveServer2-Background-Pool: Thread-52]: WARN mapreduce.JobResourceUploader: Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
Starting Job = job_1724833657149_0023, Tracking URL = http://yarnmanager:8088/proxy/application_1724833657149_0023/
Kill Command = /usr/local/hadoop/bin/mapred job  -kill job_1724833657149_0023
Hadoop job information for Stage-1: number of mappers: 1; number of reducers: 1
24/08/28 10:07:02 [HiveServer2-Background-Pool: Thread-52]: WARN mapreduce.Counters: Group org.apache.hadoop.mapred.Task$Counter is deprecated. Use org.apache.hadoop.mapreduce.TaskCounter instead
2024-08-28 10:07:02,497 Stage-1 map = 0%,  reduce = 0%
2024-08-28 10:07:11,641 Stage-1 map = 100%,  reduce = 0%, Cumulative CPU 4.64 sec
2024-08-28 10:07:27,165 Stage-1 map = 100%,  reduce = 100%, Cumulative CPU 8.15 sec
MapReduce Total cumulative CPU time: 8 seconds 150 msec
Ended Job = job_1724833657149_0023
MapReduce Jobs Launched:
Stage-Stage-1: Map: 1  Reduce: 1   Cumulative CPU: 8.15 sec   HDFS Read: 5262582 HDFS Write: 104 HDFS EC Read: 0 SUCCESS
Total MapReduce CPU Time Spent: 8 seconds 150 msec
+----------------+
| num_registros  |
+----------------+
| 8633           |
+----------------+
1 row selected (62.645 seconds)
Beeline version 4.0.0 by Apache Hive
Closing: 0: jdbc:hive2://
24/08/28 10:07:29 [shutdown-hook-0]: WARN util.ShutdownHookManager: Shutdown in progress, cannot cancel a deleteOnExit
24/08/28 10:07:29 [shutdown-hook-0]: WARN util.ShutdownHookManager: Shutdown in progress, cannot cancel a deleteOnExit

**COMPARAMOS LA SALIDA ESPERADA CON LA OBTENIDA**

In [3]:
# realizamos la union
df_union = pd.merge( 
                     df_adjudicaciones, df_convocatorias,
                     on=['numero_procedimiento'],
                     how='inner', suffixes=('_ad', '_conv')
                   ).sort_values(by=('numero_procedimiento'))
df_union[['numero_procedimiento','nro_saf_conv','ejercicio_adjudicacion','ejercicio']].head(3)

     numero_procedimiento  nro_saf_conv  ejercicio_adjudicacion  ejercicio
6199       101-0001-CDI20           622                    2020       2020
5587       101-0002-CDI20           622                    2020       2020
4274       101-0002-LPR20           622                    2020       2020

In [17]:
# numero total de registros
df_union.shape[0]

8633

#### **Ejercicio 08.** Top N con Apache Hive.

El ejercicio número ocho consiste en extraer información sobre la tabla unión que hemos realizado. Vamos a calcular el top 5, de aquellos procedimientos que salieron más caros de lo esperado. Es decir, el monto estimado fue menor que el monto adjudicado.

Para realizar esta consulta necesitamos los campos monto_estimado, monto_adjudicado y numero_procedimiento, este último campo lo pondremos para ubicar el procedimiento. Para ordenar los resultados y quedarnos con los cinco primeros, utilizaremos las cláusulas ORDER BY campo DESC, y LIMIT numero.

In [5]:
# top 5 procedimientos
!beeline -u "jdbc:hive2://" -e \
"SELECT \
    numero_procedimiento, monto_estimado , monto_adjudicado, \
    (monto_estimado - monto_adjudicado) AS monto_diferencia \
FROM tabla_union \
ORDER BY monto_diferencia ASC \
LIMIT 5;"

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Connecting to jdbc:hive2://
Hive Session ID = d3beac5e-dfbf-4986-aaa9-4550f9221146
24/08/28 11:30:00 [main]: WARN hikari.HikariConfig: objectstore - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
24/08/28 11:30:01 [main]: WARN hikari.HikariConfig: objectstore-secondary - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
24/08/28 11:30:04 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 11:30:04 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 11:30:04 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 11:30:04 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 11:30:04 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 11:30:04 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 11:30:04 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 11:30:04 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 11:30:04 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 11:30:04 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 11:30:04 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 11:30:04 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 11:30:08 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.cpc.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 11:30:08 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.hll.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 11:30:08 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.IntersectSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 11:30:08 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.EstimateSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 11:30:08 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.ExcludeSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 11:30:08 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 11:30:08 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.tuple.ArrayOfDoublesSketchToValuesUDTF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 11:30:08 [main]: WARN session.SessionState: Configuration hive.reloadable.aux.jars.path not specified
Connected to: Apache Hive (version 4.0.0)
Driver: Hive JDBC (version 4.0.0)
Transaction isolation: TRANSACTION_REPEATABLE_READ
24/08/28 11:30:16 [88f6c7cb-5711-4f13-9665-cc611d6336e6 main]: WARN calcite.RelOptHiveTable: No Stats for default@tabla_union, Columns: monto_estimado, monto_adjudicado, numero_procedimiento
No Stats for default@tabla_union, Columns: monto_estimado, monto_adjudicado, numero_procedimiento
24/08/28 11:30:17 [HiveServer2-Background-Pool: Thread-52]: WARN ql.Driver: Hive-on-MR is deprecated in Hive 2 and may not be available in the future versions. Consider using a different execution engine (i.e. tez) or using Hive 1.X releases.
Query ID = root_20240828113009_0e21dff2-2c3a-4e5a-ae50-e64ce89e1b9c
Total jobs = 1
Launching Job 1 out of 1
Number of reduce tasks determined at compile time: 1
In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=<number>
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=<number>
In order to set a constant number of reducers:
  set mapreduce.job.reduces=<number>
WARN  : Hive-on-MR is deprecated in Hive 2 and may not be available in the future versions. Consider using a different execution engine (i.e. tez) or using Hive 1.X releases.
24/08/28 11:30:20 [HiveServer2-Background-Pool: Thread-52]: WARN mapreduce.JobResourceUploader: Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
Starting Job = job_1724833657149_0029, Tracking URL = http://yarnmanager:8088/proxy/application_1724833657149_0029/
Kill Command = /usr/local/hadoop/bin/mapred job  -kill job_1724833657149_0029
Hadoop job information for Stage-1: number of mappers: 1; number of reducers: 1
24/08/28 11:30:48 [HiveServer2-Background-Pool: Thread-52]: WARN mapreduce.Counters: Group org.apache.hadoop.mapred.Task$Counter is deprecated. Use org.apache.hadoop.mapreduce.TaskCounter instead
2024-08-28 11:30:47,975 Stage-1 map = 0%,  reduce = 0%
2024-08-28 11:31:11,965 Stage-1 map = 100%,  reduce = 0%, Cumulative CPU 6.27 sec
2024-08-28 11:31:22,090 Stage-1 map = 100%,  reduce = 100%, Cumulative CPU 10.55 sec
MapReduce Total cumulative CPU time: 10 seconds 550 msec
Ended Job = job_1724833657149_0029
MapReduce Jobs Launched:
Stage-Stage-1: Map: 1  Reduce: 1   Cumulative CPU: 10.55 sec   HDFS Read: 5262527 HDFS Write: 397 HDFS EC Read: 0 SUCCESS
Total MapReduce CPU Time Spent: 10 seconds 550 msec
+-----------------------+-----------------+-------------------+-------------------+
| numero_procedimiento  | monto_estimado  | monto_adjudicado  | monto_diferencia  |
+-----------------------+-----------------+-------------------+-------------------+
| 21-0012-CDI20         | 9.4505544E7     | 9.4505544E9       | -9.3560484E9      |
| 34-0008-LPU20         | 8.5782728E7     | 8.749442E9        | -8.6636595E9      |
| 483-0003-LPU20        | 7.1842496E7     | 7.9986637E9       | -7.9268214E9      |
| 39-0013-CDI20         | 7.7605712E7     | 7.7605709E9       | -7.682965E9       |
| 68-0013-LPU20         | 8.029E7         | 7.3471196E9       | -7.2668298E9      |
+-----------------------+-----------------+-------------------+-------------------+
5 rows selected (75.585 seconds)
Beeline version 4.0.0 by Apache Hive
Closing: 0: jdbc:hive2://
24/08/28 11:31:24 [shutdown-hook-0]: WARN util.ShutdownHookManager: Shutdown in progress, cannot cancel a deleteOnExit
24/08/28 11:31:24 [shutdown-hook-0]: WARN util.ShutdownHookManager: Shutdown in progress, cannot cancel a deleteOnExit

In [4]:
# comprobamos en el dataframe
import warnings
warnings.filterwarnings('ignore')

# calculamos la diferencia
df_diferencias = df_union[['numero_procedimiento', 'monto_estimado', 'monto']]
df_diferencias['monto_diferencia'] = (df_diferencias['monto_estimado'] - df_diferencias['monto'])
df_diferencias.sort_values(by=('monto_diferencia'), ascending = True).head(5)

     numero_procedimiento  monto_estimado       monto  monto_diferencia
7831        21-0012-CDI20     94505542.86  9450554286     -9.356049e+09
1931        34-0008-LPU20     85782730.92  8749441686     -8.663659e+09
2618       483-0003-LPU20     71842500.00  7998663854     -7.926821e+09
4097        39-0013-CDI20     77605709.53  7760570953     -7.682965e+09
1987        68-0013-LPU20     80290000.00  7347119393     -7.266829e+09

#### **Ejercicio 09.** Particiones en Apache Hive.

Este ejercicio va a utilizar tres datasets sobre la edad de los alumnos en las escuelas de Argentina.

Los campos son:

1.  ID: Identificación de la escuela.
2.  Provincia: Provincia donde se ubica la escuela.
3.  Sector: Sector de la escuela. Estatal, privado, etc.
4.  Ámbito: Ámbito donde se ubica la escuela. Rural, Urbano, etc.
5.  Grado: Curso de los alumnos

A parte de estos campos existen los campos propios de la edad: 0 años, 1 año, 2 años, etc. Y otros campos con rangos: menos de 18 años, 6 años y más, de 25 a 29 años, etc.

Vamos a descargar los tres ficheros, descomprimirlos y subirlos a HDFS para poder crear desde allí la tabla con las particiones.

In [7]:
from zipfile import ZipFile

# Descargamos el fichero y lo guardamos donde queremos
! wget https://github.com/Vega90/datasets/raw/main/argentina_alumnos_por_edad.zip \
-O /media/notebooks/argentina/argentina_alumnos_por_edad.zip

# Descomprimimos el fichero zip
zip = ZipFile('/media/notebooks/argentina/argentina_alumnos_por_edad.zip')
zip.extractall('/media/notebooks/argentina/')
zip.close()

# Eliminamos el fichero zip
! rm /media/notebooks/argentina/argentina_alumnos_por_edad.zip

--2024-08-28 11:35:40--  https://github.com/Vega90/datasets/raw/main/argentina_alumnos_por_edad.zip
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/Vega90/datasets/main/argentina_alumnos_por_edad.zip [following]
--2024-08-28 11:35:41--  https://raw.githubusercontent.com/Vega90/datasets/main/argentina_alumnos_por_edad.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6872440 (6.6M) [application/zip]
Saving to: ‘/media/notebooks/argentina/argentina_alumnos_por_edad.zip’

/media/notebooks/ar 100%[===================>]   6.55M  19.2MB/s    in 0.3s

2024-08-28 11:35:42 (19.2 MB/s) - ‘/media/notebooks/argentina/argentina_alumnos_por_edad.zip’ saved [6872440/6872440]

In [21]:
# subimos el fichero a HDFS 
! hdfs dfs -mkdir /argentina/alumnos
! hdfs dfs -mkdir /argentina/alumnos/2021
! hdfs dfs -mkdir /argentina/alumnos/2022
! hdfs dfs -mkdir /argentina/alumnos/2023
! hdfs dfs -put /media/notebooks/argentina/2021_alumnos_por_edad.csv /argentina/alumnos/2021
! hdfs dfs -put /media/notebooks/argentina/2022_alumnos_por_edad.csv /argentina/alumnos/2022
! hdfs dfs -put /media/notebooks/argentina/2023_alumnos_por_edad.csv /argentina/alumnos/2023

In [22]:
! hdfs dfs -ls /argentina/alumnos/2023

Found 1 items
-rw-r--r--   3 root supergroup   24548268 2024-08-28 10:09 /argentina/alumnos/2023/2023_alumnos_por_edad.csv

Ahora vamos a crear una tabla alumnos_argentina que contenga los años 2021, 2022 y 2023, pero con los datos particionados.

Para ello debemos crear la tabla con los campos anteriores y añadir una cláusula PARTITIONED BY, con el año como campo para la partición. Además de esto omitiremos la cláusula de la localización ya que cargaremos los datos posteriormente.

In [23]:
%%writefile tabla-alumnos.hql
CREATE TABLE IF NOT EXISTS alumnos_argentina (
     ID STRING, provincia STRING, sector STRING,
     ambito STRING, grado STRING,
     0_year INT, 1_year INT, 2_year INT,
     3_year INT, 4_year INT, 5_year INT,
     6_year INT, 7_year INT, 8_year INT,
     9_year INT, 10_year INT, 11_year INT,
     12_year INT, 13_year INT, 14_year INT,
     15_year INT, 16_year INT, 17_year INT,
     18_year INT, 19_year INT, 20_year INT,
     21_year INT, 22_year INT, 23_year INT,
     24_year INT, 25_year INT, 26_year INT,
     27_year INT, 28_year INT, 29_year INT,
     less_18_year INT,  11_year_and_less INT,
     6_year_and_more INT, 18_year_and_more INT,
     25_year_and_more INT, 30_year_and_more INT, 
     20_to_24_year INT, 25_to_29_year INT
)
PARTITIONED BY (year INT)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ';'
STORED AS TEXTFILE;

Writing tabla-alumnos.hql

In [24]:
# creación tabla alumnos
!beeline -u "jdbc:hive2://" -f tabla-alumnos.hql

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Connecting to jdbc:hive2://
Hive Session ID = ab8ffa11-d25c-4999-82e6-da2b67b9fea4
24/08/28 10:09:37 [main]: WARN hikari.HikariConfig: objectstore - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
24/08/28 10:09:37 [main]: WARN hikari.HikariConfig: objectstore-secondary - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
24/08/28 10:09:40 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:09:40 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:09:40 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:09:40 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:09:40 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:09:40 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:09:40 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:09:40 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:09:40 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:09:40 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:09:40 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:09:40 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:09:44 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.cpc.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:09:44 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.hll.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:09:44 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.IntersectSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:09:44 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.EstimateSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:09:44 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.ExcludeSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:09:44 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:09:44 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.tuple.ArrayOfDoublesSketchToValuesUDTF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:09:44 [main]: WARN session.SessionState: Configuration hive.reloadable.aux.jars.path not specified
Connected to: Apache Hive (version 4.0.0)
Driver: Hive JDBC (version 4.0.0)
Transaction isolation: TRANSACTION_REPEATABLE_READ
0: jdbc:hive2://> CREATE TABLE IF NOT EXISTS alumnos_argentina (
. . . . . . . . >      ID STRING, provincia STRING, sector STRING,
. . . . . . . . >      ambito STRING, grado STRING,
. . . . . . . . >      0_year INT, 1_year INT, 2_year INT,
. . . . . . . . >      3_year INT, 4_year INT, 5_year INT,
. . . . . . . . >      6_year INT, 7_year INT, 8_year INT,
. . . . . . . . >      9_year INT, 10_year INT, 11_year INT,
. . . . . . . . >      12_year INT, 13_year INT, 14_year INT,
. . . . . . . . >      15_year INT, 16_year INT, 17_year INT,
. . . . . . . . >      18_year INT, 19_year INT, 20_year INT,
. . . . . . . . >      21_year INT, 22_year INT, 23_year INT,
. . . . . . . . >      24_year INT, 25_year INT, 26_year INT,
. . . . . . . . >      27_year INT, 28_year INT, 29_year INT,
. . . . . . . . >      less_18_year INT,  11_year_and_less INT,
. . . . . . . . >      6_year_and_more INT, 18_year_and_more INT,
. . . . . . . . >      25_year_and_more INT, 30_year_and_more INT,
. . . . . . . . >      20_to_24_year INT, 25_to_29_year INT
. . . . . . . . > )
. . . . . . . . > PARTITIONED BY (year INT)
. . . . . . . . > ROW FORMAT DELIMITED
. . . . . . . . > FIELDS TERMINATED BY ';'
. . . . . . . . > STORED AS TEXTFILE;
No rows affected (4.062 seconds)
0: jdbc:hive2://>
0: jdbc:hive2://> Closing: 0: jdbc:hive2://
24/08/28 10:09:49 [shutdown-hook-0]: WARN util.ShutdownHookManager: Shutdown in progress, cannot cancel a deleteOnExit
24/08/28 10:09:49 [shutdown-hook-0]: WARN util.ShutdownHookManager: Shutdown in progress, cannot cancel a deleteOnExit

In [25]:
# carga datos 2021 
!beeline -u "jdbc:hive2://" -e \
"LOAD DATA INPATH '/argentina/alumnos/2021/2021_alumnos_por_edad.csv'  \
INTO TABLE alumnos_argentina \
PARTITION (year=2021);"

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Connecting to jdbc:hive2://
Hive Session ID = b7d91314-8614-47ab-b703-d222492b88a4
24/08/28 10:09:59 [main]: WARN hikari.HikariConfig: objectstore - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
24/08/28 10:10:00 [main]: WARN hikari.HikariConfig: objectstore-secondary - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
24/08/28 10:10:03 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:03 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:03 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:03 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:03 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:03 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:04 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:04 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:04 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:04 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:04 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:04 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:07 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.cpc.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:10:07 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.hll.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:10:07 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.IntersectSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:10:07 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.EstimateSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:10:07 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.ExcludeSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:10:07 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:10:07 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.tuple.ArrayOfDoublesSketchToValuesUDTF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:10:08 [main]: WARN session.SessionState: Configuration hive.reloadable.aux.jars.path not specified
Connected to: Apache Hive (version 4.0.0)
Driver: Hive JDBC (version 4.0.0)
Transaction isolation: TRANSACTION_REPEATABLE_READ
Loading data to table default.alumnos_argentina partition (year=2021)
24/08/28 10:10:14 [HiveServer2-Background-Pool: Thread-53]: WARN metastore.ObjectStore: Falling back to ORM path due to direct SQL failure (this is not an error): java.lang.ClassCastException: org.apache.derby.impl.jdbc.EmbedClob cannot be cast to java.lang.String at org.apache.hadoop.hive.metastore.ExceptionHandler.newMetaException(ExceptionHandler.java:152) at org.apache.hadoop.hive.metastore.Batchable.runBatched(Batchable.java:92) at org.apache.hadoop.hive.metastore.DirectSqlUpdatePart.getParams(DirectSqlUpdatePart.java:753) at org.apache.hadoop.hive.metastore.DirectSqlUpdatePart.updateParamTableInBatch(DirectSqlUpdatePart.java:720) at org.apache.hadoop.hive.metastore.DirectSqlUpdatePart.alterPartitions(DirectSqlUpdatePart.java:641) at org.apache.hadoop.hive.metastore.MetaStoreDirectSql.alterPartitions(MetaStoreDirectSql.java:598) at org.apache.hadoop.hive.metastore.ObjectStore$18.getSqlResult(ObjectStore.java:5300);
 Caused by: org.apache.derby.impl.jdbc.EmbedClob cannot be cast to java.lang.String at org.apache.hadoop.hive.metastore.DirectSqlUpdatePart$3.run(DirectSqlUpdatePart.java:764) at org.apache.hadoop.hive.metastore.Batchable.runBatched(Batchable.java:79)
No rows affected (6.005 seconds)
Beeline version 4.0.0 by Apache Hive
Closing: 0: jdbc:hive2://
24/08/28 10:10:14 [shutdown-hook-0]: WARN util.ShutdownHookManager: Shutdown in progress, cannot cancel a deleteOnExit
24/08/28 10:10:14 [shutdown-hook-0]: WARN util.ShutdownHookManager: Shutdown in progress, cannot cancel a deleteOnExit

In [26]:
# carga datos 2022 
!beeline -u "jdbc:hive2://" -e \
"LOAD DATA INPATH '/argentina/alumnos/2022/2022_alumnos_por_edad.csv'  \
INTO TABLE alumnos_argentina \
PARTITION (year=2022);"

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Connecting to jdbc:hive2://
Hive Session ID = 0a52739f-66d8-41ec-afb7-3a216102006f
24/08/28 10:10:24 [main]: WARN hikari.HikariConfig: objectstore - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
24/08/28 10:10:25 [main]: WARN hikari.HikariConfig: objectstore-secondary - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
24/08/28 10:10:27 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:27 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:27 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:27 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:27 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:27 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:27 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:27 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:27 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:27 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:27 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:27 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:31 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.cpc.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:10:31 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.hll.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:10:31 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.IntersectSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:10:31 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.EstimateSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:10:31 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.ExcludeSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:10:31 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:10:31 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.tuple.ArrayOfDoublesSketchToValuesUDTF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:10:31 [main]: WARN session.SessionState: Configuration hive.reloadable.aux.jars.path not specified
Connected to: Apache Hive (version 4.0.0)
Driver: Hive JDBC (version 4.0.0)
Transaction isolation: TRANSACTION_REPEATABLE_READ
Loading data to table default.alumnos_argentina partition (year=2022)
24/08/28 10:10:36 [HiveServer2-Background-Pool: Thread-52]: WARN metastore.ObjectStore: Falling back to ORM path due to direct SQL failure (this is not an error): java.lang.ClassCastException: org.apache.derby.impl.jdbc.EmbedClob cannot be cast to java.lang.String at org.apache.hadoop.hive.metastore.ExceptionHandler.newMetaException(ExceptionHandler.java:152) at org.apache.hadoop.hive.metastore.Batchable.runBatched(Batchable.java:92) at org.apache.hadoop.hive.metastore.DirectSqlUpdatePart.getParams(DirectSqlUpdatePart.java:753) at org.apache.hadoop.hive.metastore.DirectSqlUpdatePart.updateParamTableInBatch(DirectSqlUpdatePart.java:720) at org.apache.hadoop.hive.metastore.DirectSqlUpdatePart.alterPartitions(DirectSqlUpdatePart.java:641) at org.apache.hadoop.hive.metastore.MetaStoreDirectSql.alterPartitions(MetaStoreDirectSql.java:598) at org.apache.hadoop.hive.metastore.ObjectStore$18.getSqlResult(ObjectStore.java:5300);
 Caused by: org.apache.derby.impl.jdbc.EmbedClob cannot be cast to java.lang.String at org.apache.hadoop.hive.metastore.DirectSqlUpdatePart$3.run(DirectSqlUpdatePart.java:764) at org.apache.hadoop.hive.metastore.Batchable.runBatched(Batchable.java:79)
No rows affected (5.401 seconds)
Beeline version 4.0.0 by Apache Hive
Closing: 0: jdbc:hive2://
24/08/28 10:10:37 [shutdown-hook-0]: WARN util.ShutdownHookManager: Shutdown in progress, cannot cancel a deleteOnExit
24/08/28 10:10:37 [shutdown-hook-0]: WARN util.ShutdownHookManager: Shutdown in progress, cannot cancel a deleteOnExit

In [27]:
# carga datos 2023 
!beeline -u "jdbc:hive2://" -e \
"LOAD DATA INPATH '/argentina/alumnos/2023/2023_alumnos_por_edad.csv'  \
INTO TABLE alumnos_argentina \
PARTITION (year=2023);"

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Connecting to jdbc:hive2://
Hive Session ID = 6774325f-76dc-4d5f-a216-1f2cf2780429
24/08/28 10:10:46 [main]: WARN hikari.HikariConfig: objectstore - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
24/08/28 10:10:47 [main]: WARN hikari.HikariConfig: objectstore-secondary - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
24/08/28 10:10:49 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:49 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:49 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:49 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:49 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:49 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:50 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:50 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:50 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:50 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:50 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:50 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:10:53 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.cpc.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:10:53 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.hll.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:10:53 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.IntersectSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:10:53 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.EstimateSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:10:53 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.ExcludeSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:10:53 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:10:53 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.tuple.ArrayOfDoublesSketchToValuesUDTF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:10:53 [main]: WARN session.SessionState: Configuration hive.reloadable.aux.jars.path not specified
Connected to: Apache Hive (version 4.0.0)
Driver: Hive JDBC (version 4.0.0)
Transaction isolation: TRANSACTION_REPEATABLE_READ
Loading data to table default.alumnos_argentina partition (year=2023)
24/08/28 10:10:59 [HiveServer2-Background-Pool: Thread-52]: WARN metastore.ObjectStore: Falling back to ORM path due to direct SQL failure (this is not an error): java.lang.ClassCastException: org.apache.derby.impl.jdbc.EmbedClob cannot be cast to java.lang.String at org.apache.hadoop.hive.metastore.ExceptionHandler.newMetaException(ExceptionHandler.java:152) at org.apache.hadoop.hive.metastore.Batchable.runBatched(Batchable.java:92) at org.apache.hadoop.hive.metastore.DirectSqlUpdatePart.getParams(DirectSqlUpdatePart.java:753) at org.apache.hadoop.hive.metastore.DirectSqlUpdatePart.updateParamTableInBatch(DirectSqlUpdatePart.java:720) at org.apache.hadoop.hive.metastore.DirectSqlUpdatePart.alterPartitions(DirectSqlUpdatePart.java:641) at org.apache.hadoop.hive.metastore.MetaStoreDirectSql.alterPartitions(MetaStoreDirectSql.java:598) at org.apache.hadoop.hive.metastore.ObjectStore$18.getSqlResult(ObjectStore.java:5300);
 Caused by: org.apache.derby.impl.jdbc.EmbedClob cannot be cast to java.lang.String at org.apache.hadoop.hive.metastore.DirectSqlUpdatePart$3.run(DirectSqlUpdatePart.java:764) at org.apache.hadoop.hive.metastore.Batchable.runBatched(Batchable.java:79)
No rows affected (5.397 seconds)
Beeline version 4.0.0 by Apache Hive
Closing: 0: jdbc:hive2://
24/08/28 10:10:59 [shutdown-hook-0]: WARN util.ShutdownHookManager: Shutdown in progress, cannot cancel a deleteOnExit
24/08/28 10:10:59 [shutdown-hook-0]: WARN util.ShutdownHookManager: Shutdown in progress, cannot cancel a deleteOnExit

In [28]:
# mostramos las particiones
!beeline -u "jdbc:hive2://" -e \
"SHOW PARTITIONS alumnos_argentina;"

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Connecting to jdbc:hive2://
Hive Session ID = 4ba991a2-ff47-4db4-a378-1d18ffa6ac79
24/08/28 10:11:09 [main]: WARN hikari.HikariConfig: objectstore - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
24/08/28 10:11:10 [main]: WARN hikari.HikariConfig: objectstore-secondary - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
24/08/28 10:11:12 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:11:12 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:11:12 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:11:12 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:11:12 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:11:12 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:11:12 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:11:12 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:11:12 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:11:12 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:11:12 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:11:12 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:11:16 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.cpc.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:11:16 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.hll.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:11:16 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.IntersectSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:11:16 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.EstimateSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:11:16 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.ExcludeSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:11:16 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:11:16 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.tuple.ArrayOfDoublesSketchToValuesUDTF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:11:16 [main]: WARN session.SessionState: Configuration hive.reloadable.aux.jars.path not specified
Connected to: Apache Hive (version 4.0.0)
Driver: Hive JDBC (version 4.0.0)
Transaction isolation: TRANSACTION_REPEATABLE_READ
+------------+
| partition  |
+------------+
| year=2021  |
| year=2022  |
| year=2023  |
+------------+
3 rows selected (4.226 seconds)
Beeline version 4.0.0 by Apache Hive
Closing: 0: jdbc:hive2://
24/08/28 10:11:21 [shutdown-hook-0]: WARN util.ShutdownHookManager: Shutdown in progress, cannot cancel a deleteOnExit
24/08/28 10:11:21 [shutdown-hook-0]: WARN util.ShutdownHookManager: Shutdown in progress, cannot cancel a deleteOnExit

In [29]:
# mostramos las cinco filas primeras de 2021
!beeline -u "jdbc:hive2://" -e \
"SELECT  \
     ID, provincia, sector, ambito, grado, \
     6_year, 7_year, 8_year, 9_year \
FROM alumnos_argentina \
WHERE year=2021 \
LIMIT 5;"

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Connecting to jdbc:hive2://
Hive Session ID = 8beaf8b5-cb88-4f11-9713-586aa199ca82
24/08/28 10:11:31 [main]: WARN hikari.HikariConfig: objectstore - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
24/08/28 10:11:31 [main]: WARN hikari.HikariConfig: objectstore-secondary - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
24/08/28 10:11:33 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:11:33 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:11:33 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:11:33 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:11:33 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:11:33 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:11:34 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:11:34 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:11:34 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:11:34 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:11:34 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:11:34 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:11:37 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.cpc.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:11:37 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.hll.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:11:37 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.IntersectSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:11:37 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.EstimateSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:11:37 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.ExcludeSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:11:37 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:11:37 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.tuple.ArrayOfDoublesSketchToValuesUDTF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:11:37 [main]: WARN session.SessionState: Configuration hive.reloadable.aux.jars.path not specified
Connected to: Apache Hive (version 4.0.0)
Driver: Hive JDBC (version 4.0.0)
Transaction isolation: TRANSACTION_REPEATABLE_READ
24/08/28 10:11:45 [8259b7af-8966-44b0-9182-42afee9b6f37 main]: WARN calcite.RelOptHiveTable: No Stats for default@alumnos_argentina, Columns: grado, 9_year, 8_year, 7_year, ambito, id, provincia, sector, 6_year
No Stats for default@alumnos_argentina, Columns: grado, 9_year, 8_year, 7_year, ambito, id, provincia, sector, 6_year
24/08/28 10:11:46 [8259b7af-8966-44b0-9182-42afee9b6f37 main]: WARN optimizer.SimpleFetchOptimizer: Table default@alumnos_argentina is external table, falling back to filesystem scan.
+-----------------+------------+----------+---------+----------+---------+---------+---------+---------+
|       id        | provincia  |  sector  | ambito  |  grado   | 6_year  | 7_year  | 8_year  | 9_year  |
+-----------------+------------+----------+---------+----------+---------+---------+---------+---------+
| 20004002000400  | Mendoza    | Estatal  | Urbano  | 1 grado  | 34      | NULL    | NULL    | NULL    |
| 20004002000400  | Mendoza    | Estatal  | Urbano  | 2 grado  | NULL    | 43      | NULL    | NULL    |
| 20004002000400  | Mendoza    | Estatal  | Urbano  | 3 grado  | NULL    | NULL    | 31      | 2       |
| 20004002000400  | Mendoza    | Estatal  | Urbano  | 4 grado  | NULL    | NULL    | NULL    | 41      |
| 20004002000400  | Mendoza    | Estatal  | Urbano  | 5 grado  | NULL    | NULL    | NULL    | NULL    |
+-----------------+------------+----------+---------+----------+---------+---------+---------+---------+
5 rows selected (9.223 seconds)
Beeline version 4.0.0 by Apache Hive
Closing: 0: jdbc:hive2://
24/08/28 10:11:47 [shutdown-hook-0]: WARN util.ShutdownHookManager: Shutdown in progress, cannot cancel a deleteOnExit
24/08/28 10:11:47 [shutdown-hook-0]: WARN util.ShutdownHookManager: Shutdown in progress, cannot cancel a deleteOnExit

In [8]:
import pandas as pd
# columnas de los tres ficheros
columnas = [
             'ID', 'provincia', 'sector', 'ambito', 'grado', 
             '0_year', '1_year', '2_year', '3_year', '4_year',
             '5_year', '6_year', '7_year', '8_year', '9_year',
             '10_year', '11_year', '12_year', '13_year', '14_year',
             '15_year', '16_year', '17_year', '18_year', '19_year',
             '20_year', '21_year', '22_year', '23_year', '24_year',
             '25_year', '26_year', '27_year', '28_year', '29_year',
             'less_18_year', '11_year_and_less', '6_year_and_more',
             '18_year_and_more', '25_year_and_more', '30_year_and_more',
             'cuit', 'descripcion_proveedor', 'documento_contractual',
             '20_to_24_year', '25_to_29_year'
           ]

ruta_carpeta = '/media/notebooks/argentina'
df_2021 = pd.read_csv(ruta_carpeta + '/2021_alumnos_por_edad.csv', names=columnas, delimiter=';')
df_2022 = pd.read_csv(ruta_carpeta + '/2022_alumnos_por_edad.csv', names=columnas, delimiter=';')
df_2023 = pd.read_csv(ruta_carpeta + '/2023_alumnos_por_edad.csv', names=columnas, delimiter=';')

#añadimos los años a cada columna
df_2021['year'] = 2021
df_2022['year'] = 2022
df_2023['year'] = 2023

# mostramos los primeros registros 
df_2021[['ID', 'provincia', 'sector', 'ambito', 'grado', '6_year', '7_year', '8_year', '9_year']].head(5)

,ID,provincia,sector,ambito,grado,6_year,7_year,8_year,9_year
0,20004002000400,Mendoza,Estatal,Urbano,1 grado,34.0,NaN,NaN,NaN
1,20004002000400,Mendoza,Estatal,Urbano,2 grado,NaN,43.0,NaN,NaN
2,20004002000400,Mendoza,Estatal,Urbano,3 grado,NaN,NaN,31.0,2.0
3,20004002000400,Mendoza,Estatal,Urbano,4 grado,NaN,NaN,NaN,41.0
4,20004002000400,Mendoza,Estatal,Urbano,5 grado,NaN,NaN,NaN,NaN

#### **Ejercicio 10.**

Para terminar esta sección vamos a realizar una consulta más compleja que utilice las tres particiones y realice una comparativa entre los alumnos de 11 años entre 2021 y 2023. Debemos tener en cuenta las siguientes consideraciones para realizar la consulta:

*  **WITH alumnos_year**: Agrupa los alumnos matriculados con 11 años por año en una tabla temporal.
*  **LAG**: La función LAG obtiene el valor de los alumnos de 11 años del año anterior de la tabla temporal.

In [31]:
# comparación entre los tres años para alumnos 11 años
!beeline -u "jdbc:hive2://" -e \
"WITH alumnos_year AS ( \
    SELECT  year, \
            SUM(11_year) AS alumnos_11_year \
    FROM alumnos_argentina  \
    WHERE year IN (2021, 2022, 2023) \
    GROUP BY year \
) \
SELECT  year, alumnos_11_year, \
    LAG(alumnos_11_year, 1) OVER (ORDER BY year) AS alumnos_11_anterior, \
    alumnos_11_year - (LAG(alumnos_11_year, 1) OVER (ORDER BY year)) AS diferencia  \
FROM alumnos_year \
ORDER BY year;"

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Connecting to jdbc:hive2://
Hive Session ID = a683d19d-b077-4e19-863b-ddbbf994de3e
24/08/28 10:12:00 [main]: WARN hikari.HikariConfig: objectstore - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
24/08/28 10:12:00 [main]: WARN hikari.HikariConfig: objectstore-secondary - leakDetectionThreshold is less than 2000ms or more than maxLifetime, disabling it.
24/08/28 10:12:03 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:12:03 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:12:03 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:12:03 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:12:03 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:12:03 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:12:04 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:12:04 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:12:04 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:12:04 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:12:04 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:12:04 [main]: WARN DataNucleus.MetaData: Metadata has jdbc-type of null yet this is not valid. Ignored
24/08/28 10:12:07 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.cpc.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:12:07 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.hll.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:12:07 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.IntersectSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:12:07 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.EstimateSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:12:07 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.ExcludeSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:12:07 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.theta.UnionSketchUDF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:12:07 [main]: WARN exec.FunctionRegistry: UDF Class org.apache.hive.org.apache.datasketches.hive.tuple.ArrayOfDoublesSketchToValuesUDTF does not have description. Please annotate the class with the org.apache.hadoop.hive.ql.exec.Description annotation and provide the description of the function.
24/08/28 10:12:08 [main]: WARN session.SessionState: Configuration hive.reloadable.aux.jars.path not specified
Connected to: Apache Hive (version 4.0.0)
Driver: Hive JDBC (version 4.0.0)
Transaction isolation: TRANSACTION_REPEATABLE_READ
24/08/28 10:12:17 [70d3d44f-0d1f-4fb1-9f67-ac008b11d871 main]: WARN calcite.RelOptHiveTable: No Stats for default@alumnos_argentina, Columns: 11_year
No Stats for default@alumnos_argentina, Columns: 11_year
24/08/28 10:12:19 [HiveServer2-Background-Pool: Thread-56]: WARN ql.Driver: Hive-on-MR is deprecated in Hive 2 and may not be available in the future versions. Consider using a different execution engine (i.e. tez) or using Hive 1.X releases.
Query ID = root_20240828101208_b4b71dc9-c4e3-4639-8bb7-79cef3a4da3d
Total jobs = 3
Launching Job 1 out of 3
Number of reduce tasks not specified. Estimated from input data size: 1
In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=<number>
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=<number>
In order to set a constant number of reducers:
  set mapreduce.job.reduces=<number>
WARN  : Hive-on-MR is deprecated in Hive 2 and may not be available in the future versions. Consider using a different execution engine (i.e. tez) or using Hive 1.X releases.
24/08/28 10:12:22 [HiveServer2-Background-Pool: Thread-56]: WARN mapreduce.JobResourceUploader: Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
Starting Job = job_1724833657149_0025, Tracking URL = http://yarnmanager:8088/proxy/application_1724833657149_0025/
Kill Command = /usr/local/hadoop/bin/mapred job  -kill job_1724833657149_0025
Hadoop job information for Stage-1: number of mappers: 2; number of reducers: 1
24/08/28 10:12:58 [HiveServer2-Background-Pool: Thread-56]: WARN mapreduce.Counters: Group org.apache.hadoop.mapred.Task$Counter is deprecated. Use org.apache.hadoop.mapreduce.TaskCounter instead
2024-08-28 10:12:58,804 Stage-1 map = 0%,  reduce = 0%
2024-08-28 10:13:30,353 Stage-1 map = 50%,  reduce = 0%, Cumulative CPU 5.83 sec
2024-08-28 10:13:32,680 Stage-1 map = 100%,  reduce = 0%, Cumulative CPU 13.09 sec
2024-08-28 10:13:41,382 Stage-1 map = 100%,  reduce = 100%, Cumulative CPU 16.76 sec
MapReduce Total cumulative CPU time: 16 seconds 760 msec
Ended Job = job_1724833657149_0025
Launching Job 2 out of 3
Number of reduce tasks not specified. Estimated from input data size: 1
In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=<number>
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=<number>
In order to set a constant number of reducers:
  set mapreduce.job.reduces=<number>
24/08/28 10:13:44 [HiveServer2-Background-Pool: Thread-56]: WARN mapreduce.JobResourceUploader: Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
Starting Job = job_1724833657149_0026, Tracking URL = http://yarnmanager:8088/proxy/application_1724833657149_0026/
Kill Command = /usr/local/hadoop/bin/mapred job  -kill job_1724833657149_0026
Hadoop job information for Stage-2: number of mappers: 1; number of reducers: 1
24/08/28 10:14:08 [HiveServer2-Background-Pool: Thread-56]: WARN mapreduce.Counters: Group org.apache.hadoop.mapred.Task$Counter is deprecated. Use org.apache.hadoop.mapreduce.TaskCounter instead
2024-08-28 10:14:08,047 Stage-2 map = 0%,  reduce = 0%
2024-08-28 10:14:24,712 Stage-2 map = 100%,  reduce = 0%, Cumulative CPU 5.65 sec
2024-08-28 10:14:37,063 Stage-2 map = 100%,  reduce = 100%, Cumulative CPU 11.23 sec
MapReduce Total cumulative CPU time: 11 seconds 230 msec
Ended Job = job_1724833657149_0026
Launching Job 3 out of 3
Number of reduce tasks determined at compile time: 1
In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=<number>
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=<number>
In order to set a constant number of reducers:
  set mapreduce.job.reduces=<number>
24/08/28 10:14:39 [HiveServer2-Background-Pool: Thread-56]: WARN mapreduce.JobResourceUploader: Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
Starting Job = job_1724833657149_0027, Tracking URL = http://yarnmanager:8088/proxy/application_1724833657149_0027/
Kill Command = /usr/local/hadoop/bin/mapred job  -kill job_1724833657149_0027
Hadoop job information for Stage-3: number of mappers: 1; number of reducers: 1
24/08/28 10:15:04 [HiveServer2-Background-Pool: Thread-56]: WARN mapreduce.Counters: Group org.apache.hadoop.mapred.Task$Counter is deprecated. Use org.apache.hadoop.mapreduce.TaskCounter instead
2024-08-28 10:15:04,010 Stage-3 map = 0%,  reduce = 0%
2024-08-28 10:15:20,471 Stage-3 map = 100%,  reduce = 0%, Cumulative CPU 4.42 sec
2024-08-28 10:15:30,117 Stage-3 map = 100%,  reduce = 100%, Cumulative CPU 8.54 sec
MapReduce Total cumulative CPU time: 8 seconds 540 msec
Ended Job = job_1724833657149_0027
MapReduce Jobs Launched:
Stage-Stage-1: Map: 2  Reduce: 1   Cumulative CPU: 16.76 sec   HDFS Read: 73802277 HDFS Write: 168 HDFS EC Read: 0 SUCCESS
Stage-Stage-2: Map: 1  Reduce: 1   Cumulative CPU: 11.23 sec   HDFS Read: 11460 HDFS Write: 182 HDFS EC Read: 0 SUCCESS
Stage-Stage-3: Map: 1  Reduce: 1   Cumulative CPU: 8.54 sec   HDFS Read: 9640 HDFS Write: 191 HDFS EC Read: 0 SUCCESS
Total MapReduce CPU Time Spent: 36 seconds 530 msec
+-------+------------------+----------------------+-------------+
| year  | alumnos_11_year  | alumnos_11_anterior  | diferencia  |
+-------+------------------+----------------------+-------------+
| 2021  | 746113           | NULL                 | NULL        |
| 2022  | 751849           | 746113               | 5736        |
| 2023  | 738572           | 751849               | -13277      |
+-------+------------------+----------------------+-------------+
3 rows selected (204.242 seconds)
Beeline version 4.0.0 by Apache Hive
Closing: 0: jdbc:hive2://
24/08/28 10:15:32 [shutdown-hook-0]: WARN util.ShutdownHookManager: Shutdown in progress, cannot cancel a deleteOnExit
24/08/28 10:15:32 [shutdown-hook-0]: WARN util.ShutdownHookManager: Shutdown in progress, cannot cancel a deleteOnExit

In [9]:
# comprobamos en el dataframe
df_combinado = pd.concat([df_2021, df_2022, df_2023], ignore_index=True)

# agrupamos y sumamos los alumnos con 11 años por año
df_comparativa = df_combinado.groupby('year')['11_year'].sum().reset_index()

# realizamos la comparativa
df_comparativa['alumnos_11_anterior'] = df_comparativa['11_year'].shift(1)
df_comparativa['diferencia'] = df_comparativa['11_year'] - df_comparativa['alumnos_11_anterior']
df_comparativa

   year   11_year  alumnos_11_anterior  diferencia
0  2021  746113.0                  NaN         NaN
1  2022  751849.0             746113.0      5736.0
2  2023  738572.0             751849.0    -13277.0